version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=
      - PGID=
      - TZ=
    volumes:
      - .radarr/config:/config
      - /path/to/movies/directory:/movies
    ports:
      - 7878:7878
    restart: always
    networks:
      - traefik
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.radarr.entrypoints=web,websecure"
          - "traefik.http.routers.radarr.rule=Host(`example.com`)"
          - "traefik.http.routers.radarr.service=radarr-service"
          - "traefik.http.services.radarr-service.loadbalancer.server.port=7878"
          - "traefik.http.routers.radarr.tls=true"
          - "traefik.http.routers.radarr.tls.certresolver=production"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_movies
    environment:
      - PUID=
      - PGID=
      - TZ=
      - WEBUI_PORT=8087
      - TORRENTING_PORT=6881
    volumes:
      - ./radarr/qbittorrent/config:/config
      - /path/to/movies/directory:/downloads
    ports:
      - 8087:8087
      - 6881:6881
      - 6881:6881/udp
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrentmovies.entrypoints=web,websecure
      - traefik.http.routers.torrentmovies.rule=Host(`example.com`)
      - traefik.http.routers.torrentmovies.service=torrentmovies-service
      - traefik.http.services.torrentmovies-service.loadbalancer.server.port=8087
      - traefik.http.routers.torrentmovies.tls=true
      - traefik.http.routers.torrentmovies.tls.certresolver=production
networks:
  traefik:
    external: true
