version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: nginx-php
    restart: always
    ports:
      - '80:80' # change port on left to unmappe port
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cloudflare
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    container_name: nginx-php-fpm
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - cloudflare

networks:
  cloudflare: # same network as in #cloudflare-tunnel
    external: true
