version: "3"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=
      - PGID=
      - TZ=
    volumes:
      - /path/to/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: always
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=web,websecure
      - traefik.http.routers.prowlarr.rule=Host(`example.com`)
      - traefik.http.routers.prowlarr.service=prowlarr-service
      - traefik.http.services.prowlarr-service.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=production
networks:
  traefik:
    external: true