version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    ports:
      - '7575:7575'
    networks:
      - traefik
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.homarr.entrypoints=web,websecure"
          - "traefik.http.routers.homarr.rule=Host(`example.com`)"
          - "traefik.http.routers.homarr.service=homarr-service"
          - "traefik.http.services.homarr-service.loadbalancer.server.port=7575"
          - "traefik.http.routers.homarr.tls=true"
          - "traefik.http.routers.homarr.tls.certresolver=production"
networks:
  traefik:
    external: true
