version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-discord
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - TZ=
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://{$DISCORD_WEBHOOK_TOKEN}@{$DISCORD_WEBHOOK_ID}?splitlines=yes
    restart: always
