version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=
      - PGID=
      - TZ=
      - AUTO_UPDATE=true #optional
    volumes:
      - .jackett/config:/config
      - .downloads/:/downloads
    ports:
      - 9117:9117
    restart: always
    networks:
      - traefik
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.jackett.entrypoints=web,websecure"
          - "traefik.http.routers.jackett.rule=Host(`example.com`)"
          - "traefik.http.routers.jackett.service=jackett-service"
          - "traefik.http.services.jackett-service.loadbalancer.server.port=9117"
          - "traefik.http.routers.jackett.tls=true"
          - "traefik.http.routers.jackett.tls.certresolver=production"
networks:
  traefik:
    external: true
