version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://example.com
      VIKUNJA_DATABASE_HOST: db:3306
      VIKUNJA_DATABASE_PASSWORD: db_passwd
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: db_user
      VIKUNJA_DATABASE_DATABASE: db_name
      VIKUNJA_SERVICE_JWTSECRET: 
    volumes: 
      - ./files:/app/vikunja/files
    networks:
      - traefik
    depends_on:
      db:
        condition: service_healthy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.entrypoints=web,websecure"
      - "traefik.http.routers.vikunja.rule=Host(`example.com`)"
      - "traefik.http.routers.vikunja.service=vikunja-service"
      - "traefik.http.services.vikunja-service.loadbalancer.server.port=3456"
      - "traefik.http.routers.vikunja.tls=true"
      - "traefik.http.routers.vikunja.tls.certresolver=production"
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: db_root_passwd
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_passwd
      MYSQL_DATABASE: db_name
    networks:
      - traefik
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u vikunja --password=exTDn159y."]
      interval: 2s
      start_period: 30s

networks:
  traefik:
    external: true
