version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=
      - PGID=
      - TZ=
    volumes:
      - .sonarr/config:/config
      - /path/to/tvshows/directory:/tv
    ports:
      - 8989:8989
    restart: always
    networks:
      - traefik
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.sonarr.entrypoints=web,websecure"
          - "traefik.http.routers.sonarr.rule=Host(`example.com`)"
          - "traefik.http.routers.sonarr.service=sonarr-service"
          - "traefik.http.services.sonarr-service.loadbalancer.server.port=8989"
          - "traefik.http.routers.sonarr.tls=true"
          - "traefik.http.routers.sonarr.tls.certresolver=production"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_shows
    environment:
      - PUID=
      - PGID=
      - TZ=
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6882
    volumes:
      - .sonarr/config:/config
      - /path/to/tvshows/directory:/downloads
    ports:
      - 8088:8088
      - 6882:6881
      - 6882:6881/udp
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrentshows.entrypoints=web,websecure
      - traefik.http.routers.torrentshows.rule=Host(`example.com`)
      - traefik.http.routers.torrentshows.service=torrentshows-service
      - traefik.http.services.torrentshows-service.loadbalancer.server.port=8088
      - traefik.http.routers.torrentshows.tls=true
      - traefik.http.routers.torrentshows.tls.certresolver=production
networks:
  traefik:
    external: true
