services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.entrypoints=web,websecure
      - traefik.http.routers.uptime-kuma.rule=Host(`example.com`)
      - traefik.http.routers.uptime-kuma.service=uptime-kuma-service
      - traefik.http.services.uptime-kuma-service.loadbalancer.server.port=3001
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=production
networks:
  traefik:
    external: true