version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: always
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.entrypoints=web,websecure
      - traefik.http.routers.dockge.rule=Host(`example.com`)
      - traefik.http.routers.dockge.service=dockge-service
      - traefik.http.services.dockge-service.loadbalancer.server.port=5001
      - traefik.http.routers.dockge.tls=true
      - traefik.http.routers.dockge.tls.certresolver=production
networks:
  traefik:
    external: true